apiVersion: v1
entries:
  jaeger-all-in-one:
  - apiVersion: v2
    appVersion: 1.21.0
    created: "2020-12-08T16:41:59.5629478+01:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 73c8dd42c9e7aee703a289e7ababf398a86d299c996241972de4e5fedf957298
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-08T16:41:59.5619467+01:00"
