apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-all-in-one.fullname" . }}
  labels:
    {{- include "jaeger-all-in-one.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6831
      targetPort: udp-com-thr
      protocol: UDP
      name: udp-com-thr
    - port: 6832
      targetPort: udp-bin-thr
      protocol: UDP
      name: udp-bin-thr
    - port: 5775
      targetPort: udp-bin-thr-o
      protocol: UDP
      name: udp-bin-thr-o
    - port: 5778
      targetPort: http-configs
      protocol: TCP
      name: http-configs
    - port: {{ .Values.service.port }}
      targetPort: http-ui
      protocol: TCP
      name: http-ui
    - port: 14269
      targetPort: http-admin
      protocol: TCP
      name: http-admin
  selector:
    {{- include "jaeger-all-in-one.selectorLabels" . | nindent 4 }}
